---
- hosts: all
  become: yes
  pre_tasks:
    - name: Set up havce infra SSH keys
      ansible.posix.authorized_key:
        user: ubuntu
        state: present
        key: '{{ item }}'
      with_url:
        - https://github.com/ferr0x.keys
         
    - name: Install wireguard
      apt:
        pkg:
          - wireguard
        state: latest
        update_cache: true

  roles:
    - docker


